sudo: required

language: bash

services:
  - docker

env:
  - PHP_RUNTIME=5.4 PHP_COVERAGE=''
  - PHP_RUNTIME=5.5 PHP_COVERAGE=''
  - PHP_RUNTIME=5.6 PHP_COVERAGE='--coverage-clover coverage.clover'
  - PHP_RUNTIME=7.0 PHP_COVERAGE=''

before_install:
  # https://github.com/travis-ci/travis-ci/issues/4778
  # https://github.com/zuazo/kitchen-in-travis-native/issues/1#issuecomment-142230889
  - sudo iptables -L DOCKER || (echo "DOCKER iptables chain missing"; sudo iptables -N DOCKER)

install:
  - ./dockerfile.sh | docker build -t msgpack -

script:
  - docker run --rm --name msgpack -v $(pwd):/msgpack -w /msgpack msgpack

after_script:
  - >
    if [[ ! -z "$PHP_COVERAGE" ]]; then
      docker run --rm --name msgpack -v $(pwd):/msgpack -w /msgpack msgpack bash -c "
        curl -sSOL https://scrutinizer-ci.com/ocular.phar &&
        php ocular.phar code-coverage:upload --format=php-clover coverage.clover
      "
    fi
